apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
namespace: dev
images:
- name: cnych/gitops-webapp
  newTag: 3f520d48
